export enum NotificationType {
    ADDED_TO_OUTING = 'ADDED_TO_OUTING',
    ADDED_TO_ACTIVITY = 'ADDED_TO_ACTIVITY',
    SETTLE_UP_REMINDER = 'SETTLE_UP_REMINDER',
    ADDED_TO_GROUP = 'ADDED_TO_GROUP'
}